import React, { useEffect, useMemo, useState } from 'react';
import { Chamado, Department } from '../types';
import { Search, TicketCheck, Clock3, AlertTriangle, CheckCircle2, Loader2 } from 'lucide-react';
import { ChamadoDetalhe } from './ChamadoDetalhe';

interface Props { department: Department; refreshKey: number; onOpenNewChamado: () => void; }
export const ChamadosDepartamento: React.FC<Props> = ({ department, refreshKey, onOpenNewChamado }) => {
  const [itens,setItens]=useState<Chamado[]>([]); const [selecionado,setSelecionado]=useState<Chamado|null>(null); const [busca,setBusca]=useState(''); const [status,setStatus]=useState('Ativos'); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState('');
  const carregar=()=>{setCarregando(true);setErro('');fetch(`/api/chamados?escopo=departamento&departamentoId=${encodeURIComponent(department.id)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItens(d)}).catch(e=>setErro(e.message)).finally(()=>setCarregando(false));};
  useEffect(carregar,[department.id,refreshKey]);
  const filtrados=useMemo(()=>itens.filter(c=>{const ativo=!['Encerrado','Cancelado'].includes(c.status);const filtro=status==='Todos'||(status==='Ativos'&&ativo)||c.status===status;const q=busca.toLowerCase();return filtro&&(!q||`${c.protocolo} ${c.assunto} ${c.solicitanteNome} ${c.responsavel||''}`.toLowerCase().includes(q));}),[itens,busca,status]);
  const atualizar=(c:Chamado)=>{setItens(v=>v.map(i=>i.id===c.id?c:i));setSelecionado(c)};
  const ativos=itens.filter(c=>!['Encerrado','Cancelado'].includes(c.status));
  return <div className="space-y-5"><div className="grid sm:grid-cols-3 gap-3"><Kpi icon={Clock3} label="Em aberto" value={ativos.filter(c=>c.status==='Aberto').length}/><Kpi icon={AlertTriangle} label="Em andamento" value={ativos.filter(c=>c.status!=='Aberto').length}/><Kpi icon={CheckCircle2} label="Encerrados" value={itens.filter(c=>c.status==='Encerrado').length}/></div>
    <div className="bg-white border rounded-2xl p-4 flex flex-col md:flex-row gap-3 md:items-center"><div className="relative flex-1"><Search className="absolute w-4 h-4 left-3 top-3 text-neutral-400"/><input className="w-full border rounded-xl pl-9 pr-3 py-2.5 text-xs outline-none focus:border-yellow-400" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Protocolo, assunto, solicitante ou responsável"/></div><select className="border rounded-xl px-3 py-2.5 text-xs" value={status} onChange={e=>setStatus(e.target.value)}>{['Ativos','Todos','Aberto','Em atendimento','Aguardando solicitante','Resolvido','Encerrado','Cancelado'].map(s=><option key={s}>{s}</option>)}</select><button onClick={onOpenNewChamado} className="bg-yellow-400 rounded-xl px-4 py-2.5 text-xs font-black">+ Abrir chamado</button></div>
    {erro&&<div className="p-4 bg-red-50 text-red-700 rounded-xl text-xs">{erro}</div>}{carregando?<div className="p-12 flex justify-center"><Loader2 className="animate-spin"/></div>:filtrados.length===0?<div className="p-12 text-center border border-dashed rounded-2xl text-neutral-400"><TicketCheck className="w-8 h-8 mx-auto mb-2"/><p className="text-sm font-bold">Nenhum chamado nesta fila</p></div>:<div className="bg-white border rounded-2xl overflow-hidden divide-y">{filtrados.map(c=><button key={c.id} onClick={()=>setSelecionado(c)} className="w-full text-left p-4 hover:bg-yellow-50 transition grid md:grid-cols-[120px_1fr_150px_120px] gap-2 md:items-center"><div><p className="font-mono text-xs font-black text-yellow-700">{c.protocolo}</p><p className="text-[10px] text-neutral-400 mt-1">{new Date(c.criadoEm).toLocaleDateString('pt-BR')}</p></div><div className="min-w-0"><p className="text-sm font-bold truncate">{c.assunto}</p><p className="text-xs text-neutral-500 truncate">{c.solicitanteNome} · {c.categoria}</p></div><p className="text-xs text-neutral-600">{c.responsavel||'Não atribuído'}</p><span className={`justify-self-start px-2 py-1 rounded-full text-[10px] font-bold ${c.prioridade==='Urgente'?'bg-red-100 text-red-700':'bg-neutral-100 text-neutral-600'}`}>{c.status}</span></button>)}</div>}
    {selecionado&&<ChamadoDetalhe chamado={selecionado} podeAtender onClose={()=>setSelecionado(null)} onUpdated={atualizar}/>}</div>;
};
const Kpi=({icon:Icon,label,value}:{icon:any;label:string;value:number})=><div className="bg-white border rounded-2xl p-4 flex items-center gap-3"><div className="p-2 rounded-xl bg-yellow-50"><Icon className="w-5 h-5 text-yellow-600"/></div><div><p className="text-2xl font-black">{value}</p><p className="text-[10px] uppercase font-bold text-neutral-400">{label}</p></div></div>;
