import React, { useEffect, useState } from 'react';
import { Chamado } from '../types';
import { X, Send, Lock, Loader2, UserRound, MapPin, Monitor, CalendarDays, CheckCircle2 } from 'lucide-react';

interface Props { chamado: Chamado; podeAtender: boolean; onClose: () => void; onUpdated: (chamado: Chamado) => void; }
const data = (valor?: string) => valor ? new Date(valor).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : '—';

export const ChamadoDetalhe: React.FC<Props> = ({ chamado, podeAtender, onClose, onUpdated }) => {
  const [responsavel, setResponsavel] = useState(chamado.responsavel || ''); const [prazo, setPrazo] = useState(chamado.prazo?.slice(0,16) || '');
  const [prioridade, setPrioridade] = useState(chamado.prioridade); const [solucao, setSolucao] = useState(chamado.solucao || '');
  const [conteudo, setConteudo] = useState(''); const [interna, setInterna] = useState(false); const [ocupado, setOcupado] = useState(false); const [erro, setErro] = useState('');
  useEffect(()=>{ setResponsavel(chamado.responsavel || ''); setPrazo(chamado.prazo?.slice(0,16) || ''); setPrioridade(chamado.prioridade); setSolucao(chamado.solucao || ''); },[chamado.id]);
  const requisicao = async (url: string, method: string, body: any) => { setOcupado(true); setErro(''); try { const res = await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const dados=await res.json(); if(!res.ok) throw new Error(dados.error||'Não foi possível concluir a ação.'); onUpdated(dados); return true; } catch(error:any){setErro(error.message); return false;} finally{setOcupado(false);} };
  const atualizar = (patch: any) => requisicao(`/api/chamados/${chamado.id}`,'PATCH',patch);
  const enviar = async (e: React.FormEvent) => { e.preventDefault(); if(!conteudo.trim()) return; if(await requisicao(`/api/chamados/${chamado.id}/interacoes`,'POST',{conteudo,tipo:interna?'nota_interna':'mensagem'})) setConteudo(''); };
  const status = async (novo: Chamado['status']) => { if((novo==='Resolvido'||novo==='Encerrado')&&!solucao.trim()){setErro('Registre a solução antes de resolver ou encerrar.');return;} await atualizar({status:novo,solucao}); };
  const input='w-full rounded-xl border border-neutral-200 px-3 py-2 text-sm outline-none focus:border-yellow-400';
  return <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm p-3 sm:p-6 flex justify-end"><div className="bg-neutral-50 w-full max-w-4xl h-full rounded-[2rem] shadow-2xl overflow-y-auto">
    <div className="sticky top-0 z-10 bg-white border-b px-5 sm:px-7 py-5 flex items-start gap-4 rounded-t-[2rem]"><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 items-center"><span className="font-mono text-xs font-black text-yellow-700">{chamado.protocolo}</span><span className="px-2 py-1 bg-neutral-100 rounded-full text-[10px] font-black uppercase">{chamado.status}</span><span className="px-2 py-1 bg-red-50 text-red-700 rounded-full text-[10px] font-bold">{chamado.prioridade}</span></div><h2 className="font-black text-lg text-neutral-900 mt-2">{chamado.assunto}</h2><p className="text-xs text-neutral-500 mt-1">{chamado.departamentoNome} · {chamado.categoria}</p></div><button onClick={onClose} className="p-2 rounded-full hover:bg-neutral-100"><X className="w-5 h-5"/></button></div>
    <div className="p-5 sm:p-7 grid lg:grid-cols-[1fr_310px] gap-6">
      <div className="space-y-5"><section className="bg-white border rounded-2xl p-5"><h3 className="text-xs font-black uppercase text-neutral-500 mb-3">Solicitação</h3><p className="text-sm leading-6 whitespace-pre-wrap">{chamado.descricao}</p>{chamado.impacto&&<div className="mt-4 p-3 bg-amber-50 border border-amber-100 rounded-xl"><strong className="text-xs">Impacto informado</strong><p className="text-xs mt-1">{chamado.impacto}</p></div>}</section>
        <section className="bg-white border rounded-2xl p-5"><h3 className="text-xs font-black uppercase text-neutral-500 mb-4">Histórico e comunicação</h3><div className="space-y-3">{chamado.interacoes.map((item)=><div key={item.id} className={`rounded-xl p-3 border ${item.tipo==='nota_interna'?'bg-violet-50 border-violet-200':item.tipo==='evento'?'bg-neutral-50 border-neutral-100':'bg-white border-neutral-200'}`}><div className="flex justify-between gap-3 text-[10px] text-neutral-500"><strong className="text-neutral-800 flex items-center gap-1">{item.tipo==='nota_interna'&&<Lock className="w-3 h-3"/>}{item.autorNome}</strong><span>{data(item.criadoEm)}</span></div><p className="text-xs mt-1.5 whitespace-pre-wrap">{item.conteudo}</p></div>)}</div>
          <form onSubmit={enviar} className="mt-4 border-t pt-4"><textarea className={input} rows={3} value={conteudo} onChange={(e)=>setConteudo(e.target.value)} placeholder="Escreva uma atualização ou resposta..."/>{podeAtender&&<label className="mt-2 flex items-center gap-2 text-xs font-semibold text-neutral-600"><input type="checkbox" checked={interna} onChange={(e)=>setInterna(e.target.checked)}/> Nota interna (o solicitante não visualiza)</label>}<button disabled={ocupado||!conteudo.trim()} className="mt-3 bg-neutral-900 text-white rounded-full px-4 py-2 text-xs font-bold flex gap-2 items-center disabled:opacity-50"><Send className="w-3.5 h-3.5"/>Registrar interação</button></form>
        </section>
      </div>
      <aside className="space-y-4"><section className="bg-white border rounded-2xl p-5 space-y-3"><h3 className="text-xs font-black uppercase text-neutral-500">Informações</h3><Info icon={UserRound} label="Solicitante" value={`${chamado.solicitanteNome}\n${chamado.solicitanteEmail}`}/><Info icon={MapPin} label="Local" value={chamado.local}/><Info icon={Monitor} label="Patrimônio" value={chamado.patrimonio}/><Info icon={CalendarDays} label="Data desejada" value={chamado.dataDesejada ? new Date(`${chamado.dataDesejada}T12:00:00`).toLocaleDateString('pt-BR') : undefined}/><div className="text-[11px] text-neutral-500 pt-2 border-t">Aberto em {data(chamado.criadoEm)}<br/>Atualizado em {data(chamado.atualizadoEm)}</div></section>
        {podeAtender&&<section className="bg-white border rounded-2xl p-5 space-y-3"><h3 className="text-xs font-black uppercase text-neutral-500">Atendimento</h3><label className="block text-xs font-bold">Responsável<input className={`${input} mt-1`} value={responsavel} onChange={(e)=>setResponsavel(e.target.value)} placeholder="Nome do atendente"/></label><label className="block text-xs font-bold">Prazo<input type="datetime-local" className={`${input} mt-1`} value={prazo} onChange={(e)=>setPrazo(e.target.value)}/></label><label className="block text-xs font-bold">Prioridade<select className={`${input} mt-1`} value={prioridade} onChange={(e)=>setPrioridade(e.target.value as any)}>{['Baixa','Média','Alta','Urgente'].map((p)=><option key={p}>{p}</option>)}</select></label><label className="block text-xs font-bold">Solução / conclusão<textarea rows={4} className={`${input} mt-1`} value={solucao} onChange={(e)=>setSolucao(e.target.value)} placeholder="Diagnóstico, ações executadas e resultado"/></label><button disabled={ocupado} onClick={()=>atualizar({responsavel,prazo,prioridade,solucao})} className="w-full rounded-xl bg-neutral-100 py-2.5 text-xs font-black">Salvar informações</button><div className="grid grid-cols-2 gap-2 pt-2">{chamado.status==='Aberto'&&<Acao onClick={()=>status('Em atendimento')}>Iniciar</Acao>}{!['Encerrado','Cancelado'].includes(chamado.status)&&<Acao onClick={()=>status('Aguardando solicitante')}>Aguardar</Acao>}{!['Resolvido','Encerrado','Cancelado'].includes(chamado.status)&&<Acao onClick={()=>status('Resolvido')}>Resolver</Acao>}{chamado.status==='Resolvido'&&<Acao onClick={()=>status('Encerrado')}>Encerrar</Acao>}{['Encerrado','Resolvido','Cancelado'].includes(chamado.status)&&<Acao onClick={()=>status('Em atendimento')}>Reabrir</Acao>}{!['Encerrado','Cancelado'].includes(chamado.status)&&<button onClick={()=>status('Cancelado')} className="rounded-xl border border-red-200 text-red-700 py-2 text-xs font-bold">Cancelar</button>}</div></section>}
        {chamado.solucao&&<section className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5"><h3 className="text-xs font-black text-emerald-800 flex gap-2"><CheckCircle2 className="w-4 h-4"/>Solução registrada</h3><p className="text-xs mt-2 whitespace-pre-wrap text-emerald-900">{chamado.solucao}</p></section>}{erro&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs">{erro}</div>}{ocupado&&<div className="flex justify-center"><Loader2 className="animate-spin text-yellow-600"/></div>}
      </aside>
    </div>
  </div></div>;
};

const Info=({icon:Icon,label,value}:{icon:any;label:string;value?:string})=>value?<div className="flex gap-2"><Icon className="w-4 h-4 text-yellow-600 shrink-0 mt-0.5"/><div><p className="text-[10px] uppercase font-bold text-neutral-400">{label}</p><p className="text-xs whitespace-pre-line">{value}</p></div></div>:null;
const Acao=({children,onClick}:{children:React.ReactNode;onClick:()=>void})=><button onClick={onClick} className="rounded-xl bg-yellow-400 text-black py-2 text-xs font-black">{children}</button>;
