import React, { useEffect, useMemo, useState } from 'react';
import { Chamado, User } from '../types';
import { LifeBuoy, Plus, Search, Loader2, Inbox, Clock3, CheckCircle2, AlertCircle } from 'lucide-react';
import { ChamadoDetalhe } from './ChamadoDetalhe';

interface Props { user: User; onOpenNewChamado: () => void; refreshKey: number; }
export const ServicosRH: React.FC<Props> = ({ onOpenNewChamado, refreshKey }) => {
  const [chamados,setChamados]=useState<Chamado[]>([]); const [selecionado,setSelecionado]=useState<Chamado|null>(null); const [busca,setBusca]=useState(''); const [status,setStatus]=useState('Todos'); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState('');
  useEffect(()=>{setCarregando(true);setErro('');fetch('/api/chamados').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setChamados(d)}).catch(e=>setErro(e.message)).finally(()=>setCarregando(false));},[refreshKey]);
  const filtrados=useMemo(()=>chamados.filter(c=>{const q=busca.toLowerCase();return(status==='Todos'||c.status===status)&&(!q||`${c.protocolo} ${c.assunto} ${c.departamentoNome} ${c.categoria}`.toLowerCase().includes(q));}),[chamados,busca,status]);
  const atualizar=(c:Chamado)=>{setChamados(v=>v.map(i=>i.id===c.id?c:i));setSelecionado(c)};
  return <div className="space-y-6 pb-12"><div className="bg-neutral-900 text-white p-6 rounded-[2rem] flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-black flex items-center gap-2"><LifeBuoy className="text-yellow-400"/>Central de chamados</h1><p className="text-xs text-neutral-400 mt-2">Abra solicitações e acompanhe cada atualização até a conclusão.</p></div><button onClick={onOpenNewChamado} className="px-5 py-3 rounded-full bg-yellow-400 text-black font-black text-sm flex items-center gap-2"><Plus className="w-4 h-4"/>Abrir chamado</button></div>
    <div className="grid sm:grid-cols-3 gap-3"><Resumo icon={Inbox} label="Total" valor={chamados.length}/><Resumo icon={Clock3} label="Em andamento" valor={chamados.filter(c=>!['Encerrado','Cancelado'].includes(c.status)).length}/><Resumo icon={CheckCircle2} label="Encerrados" valor={chamados.filter(c=>c.status==='Encerrado').length}/></div>
    <div className="bg-white border rounded-2xl p-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-neutral-400"/><input className="w-full border rounded-xl pl-9 pr-3 py-2.5 text-xs outline-none focus:border-yellow-400" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar protocolo, assunto ou departamento"/></div><select className="border rounded-xl px-3 py-2.5 text-xs" value={status} onChange={e=>setStatus(e.target.value)}>{['Todos','Aberto','Em atendimento','Aguardando solicitante','Resolvido','Encerrado','Cancelado'].map(s=><option key={s}>{s}</option>)}</select></div>
    {erro&&<div className="p-4 bg-red-50 text-red-700 rounded-xl text-xs flex gap-2"><AlertCircle className="w-4 h-4"/>{erro}</div>}{carregando?<div className="p-16 flex justify-center"><Loader2 className="animate-spin"/></div>:filtrados.length===0?<div className="p-14 text-center border border-dashed rounded-[2rem]"><Inbox className="w-9 h-9 text-neutral-300 mx-auto"/><h3 className="font-bold mt-3">Nenhum chamado encontrado</h3><p className="text-xs text-neutral-500 mt-1">Abra um chamado para iniciar uma solicitação.</p></div>:<div className="grid lg:grid-cols-2 gap-4">{filtrados.map(c=><button key={c.id} onClick={()=>setSelecionado(c)} className="bg-white border rounded-2xl p-5 text-left hover:border-yellow-400 hover:shadow-md transition"><div className="flex justify-between gap-3"><div><span className="font-mono text-xs font-black text-yellow-700">{c.protocolo}</span><p className="text-[10px] text-neutral-400 mt-1">{c.departamentoNome} · {c.categoria}</p></div><span className="h-fit px-2.5 py-1 rounded-full bg-neutral-100 text-[10px] font-black uppercase">{c.status}</span></div><h3 className="font-bold text-sm mt-4">{c.assunto}</h3><p className="text-xs text-neutral-500 mt-2 line-clamp-2">{c.descricao}</p><div className="flex justify-between border-t mt-4 pt-3 text-[10px] text-neutral-500"><span>Prioridade: <strong>{c.prioridade}</strong></span><span>{new Date(c.atualizadoEm).toLocaleDateString('pt-BR')}</span></div></button>)}</div>}
    {selecionado&&<ChamadoDetalhe chamado={selecionado} podeAtender={false} onClose={()=>setSelecionado(null)} onUpdated={atualizar}/>}</div>;
};
const Resumo=({icon:Icon,label,valor}:{icon:any;label:string;valor:number})=><div className="bg-white border rounded-2xl p-4 flex gap-3 items-center"><div className="p-2 bg-yellow-50 rounded-xl"><Icon className="w-5 h-5 text-yellow-600"/></div><div><p className="text-2xl font-black">{valor}</p><p className="text-[10px] uppercase font-bold text-neutral-400">{label}</p></div></div>;
